### ISSUE TITLE
Module 4 Block 5 : Ruby group capstone - Catalog of my things

### ISSUE THREAD

**Issue by aceDavon** [Kwaleyela-Ikafa/ruby-capstone-project#52]
## Kanban Board Setup @aceDavon, @HabibPayenda @Kwaleyela-Ikafa @Amtresu 
[Project Link](https://github.com/Kwaleyela-Ikafa/ruby-capstone-project/projects/1)

There are Four(4) persons on this Ruby Capstone project named as below:

- Team Member 1: @Kwaleyela-Ikafa 
- Team Member 2: @Amtresu 
- Team Member 3: @aceDavon 
- Team Member 4: @HabibPayenda

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Please make sure that all of the issues have a meaningful description of the feature to be implemented in that task. Currently, there're issues like the following tasks which has no description:
   - #17 
   - #50

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aceDavon** [comment]
Thanks, @ShadyShawkat for the review. I have corrected the affected cards accordingly as requested. Cheers

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @aceDavon, @HabibPayenda, @Kwaleyela-Ikafa and @Amtresu

✔️ Tasks are well set up

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
